#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export WEBVIDEO_E2E_PROFILE="${WEBVIDEO_E2E_PROFILE:-1}"
export WEBVIDEO_PROFILE_DURATION_MS="${WEBVIDEO_PROFILE_DURATION_MS:-60000}"
export WEBVIDEO_PROFILE_SAMPLE_INTERVAL_MS="${WEBVIDEO_PROFILE_SAMPLE_INTERVAL_MS:-1000}"
export WEBVIDEO_PROFILE_STREAM_SETS="${WEBVIDEO_PROFILE_STREAM_SETS:-channel-4k-crowd,channel-4k-crowd,channel-003}"
export WEBVIDEO_PROFILE_EXPECT_RTSP_SOURCES="${WEBVIDEO_PROFILE_EXPECT_RTSP_SOURCES:-channel-4k-crowd=cctv-road-crowd-1080p24,channel-003=cctv-floor-1080p}"
export WEBVIDEO_PROFILE_ASSERT_STABLE="${WEBVIDEO_PROFILE_ASSERT_STABLE:-1}"
export WEBVIDEO_PROFILE_MIN_RENDER_FPS="${WEBVIDEO_PROFILE_MIN_RENDER_FPS:-14}"
export WEBVIDEO_PROFILE_CPU="${WEBVIDEO_PROFILE_CPU:-1}"
export WEBVIDEO_PROFILE_CPU_INTERVAL_US="${WEBVIDEO_PROFILE_CPU_INTERVAL_US:-1000}"
export WEBVIDEO_DISABLE_TRACE="${WEBVIDEO_DISABLE_TRACE:-1}"
export WEBVIDEO_PLAYWRIGHT_CHROME_WEBGPU="${WEBVIDEO_PLAYWRIGHT_CHROME_WEBGPU:-1}"
export WEBVIDEO_REQUIRE_HARDWARE_WEBGPU="${WEBVIDEO_REQUIRE_HARDWARE_WEBGPU:-1}"
export WEBVIDEO_CHROME_WEBGPU_PRESET="${WEBVIDEO_CHROME_WEBGPU_PRESET:-strict-vulkan}"
export WEBVIDEO_RTSP_FPS="${WEBVIDEO_RTSP_FPS:-60}"
export WEBVIDEO_SAMPLE_FOOTAGE="${WEBVIDEO_SAMPLE_FOOTAGE:-1}"
export START_4K_RTSP="${START_4K_RTSP:-1}"
export START_4K_STRESS_RTSP="${START_4K_STRESS_RTSP:-1}"
export CHROME_WEBGPU_EXECUTABLE="${CHROME_WEBGPU_EXECUTABLE:-/usr/bin/google-chrome-stable}"

"$ROOT_DIR/scripts/test-frontend-e2e.sh" frontend/tests/e2e/vms-profile.spec.ts
