#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ -x "$ROOT_DIR/.tools/node/bin/npm" ]]; then
  NPM_BIN="$ROOT_DIR/.tools/node/bin/npm"
  export PATH="$ROOT_DIR/.tools/node/bin:$PATH"
else
  NPM_BIN="npm"
fi

case "${WEBVIDEO_TEST_PROFILE:-default}" in
  default|"")
    ;;
  hardware-gpu)
    export WEBVIDEO_PLAYWRIGHT_CHROME_WEBGPU=1
    export WEBVIDEO_REQUIRE_HARDWARE_WEBGPU=1
    : "${CHROME_WEBGPU_EXECUTABLE:=/usr/bin/google-chrome-stable}"
    export CHROME_WEBGPU_EXECUTABLE
    ;;
  long)
    export WEBVIDEO_E2E_LONG=1
    ;;
  hardware-long)
    export WEBVIDEO_PLAYWRIGHT_CHROME_WEBGPU=1
    export WEBVIDEO_REQUIRE_HARDWARE_WEBGPU=1
    export WEBVIDEO_E2E_LONG=1
    : "${CHROME_WEBGPU_EXECUTABLE:=/usr/bin/google-chrome-stable}"
    export CHROME_WEBGPU_EXECUTABLE
    ;;
  hardware-vms-profile)
    export WEBVIDEO_PLAYWRIGHT_CHROME_WEBGPU=1
    export WEBVIDEO_REQUIRE_HARDWARE_WEBGPU=1
    export WEBVIDEO_E2E_LONG=1
    export WEBVIDEO_E2E_LONG_DURATION_MS="${WEBVIDEO_E2E_LONG_DURATION_MS:-60000}"
    export WEBVIDEO_E2E_LONG_MIN_FPS_RATIO="${WEBVIDEO_E2E_LONG_MIN_FPS_RATIO:-0.80}"
    export WEBVIDEO_E2E_LONG_FRAME_INTERVAL_P95_BUDGET_MS="${WEBVIDEO_E2E_LONG_FRAME_INTERVAL_P95_BUDGET_MS:-85}"
    export WEBVIDEO_E2E_LONG_S2R_P95_BUDGET_MS="${WEBVIDEO_E2E_LONG_S2R_P95_BUDGET_MS:-750}"
    export WEBVIDEO_E2E_LONG_R2R_P95_BUDGET_MS="${WEBVIDEO_E2E_LONG_R2R_P95_BUDGET_MS:-350}"
    export WEBVIDEO_E2E_LONG_DROP_RATIO_BUDGET="${WEBVIDEO_E2E_LONG_DROP_RATIO_BUDGET:-0.02}"
    export WEBVIDEO_E2E_LONG_BACKEND_DROP_RATIO_BUDGET="${WEBVIDEO_E2E_LONG_BACKEND_DROP_RATIO_BUDGET:-0.02}"
    export WEBVIDEO_E2E_LONG_SEQUENCE_GAP_FRAME_BUDGET="${WEBVIDEO_E2E_LONG_SEQUENCE_GAP_FRAME_BUDGET:-0}"
    export WEBVIDEO_E2E_LONG_SEVERE_HITCH_BUDGET="${WEBVIDEO_E2E_LONG_SEVERE_HITCH_BUDGET:-0}"
    export WEBVIDEO_E2E_LONG_FRAME_HITCH_RATIO_BUDGET="${WEBVIDEO_E2E_LONG_FRAME_HITCH_RATIO_BUDGET:-0.01}"
    : "${CHROME_WEBGPU_EXECUTABLE:=/usr/bin/google-chrome-stable}"
    export CHROME_WEBGPU_EXECUTABLE
    ;;
  hardware-60fps)
    export WEBVIDEO_PLAYWRIGHT_CHROME_WEBGPU=1
    export WEBVIDEO_REQUIRE_HARDWARE_WEBGPU=1
    export WEBVIDEO_E2E_LONG=1
    export WEBVIDEO_RTSP_FPS="${WEBVIDEO_RTSP_FPS:-60}"
    export WEBVIDEO_E2E_LONG_DURATION_MS="${WEBVIDEO_E2E_LONG_DURATION_MS:-60000}"
    export WEBVIDEO_E2E_LONG_MIN_FPS_RATIO="${WEBVIDEO_E2E_LONG_MIN_FPS_RATIO:-0.90}"
    export WEBVIDEO_E2E_LONG_FRAME_INTERVAL_P95_BUDGET_MS="${WEBVIDEO_E2E_LONG_FRAME_INTERVAL_P95_BUDGET_MS:-24}"
    export WEBVIDEO_E2E_LONG_FRAME_INTERVAL_P99_BUDGET_MS="${WEBVIDEO_E2E_LONG_FRAME_INTERVAL_P99_BUDGET_MS:-40}"
    export WEBVIDEO_E2E_LONG_S2R_P95_BUDGET_MS="${WEBVIDEO_E2E_LONG_S2R_P95_BUDGET_MS:-500}"
    export WEBVIDEO_E2E_LONG_R2R_P95_BUDGET_MS="${WEBVIDEO_E2E_LONG_R2R_P95_BUDGET_MS:-180}"
    export WEBVIDEO_E2E_LONG_DROP_RATIO_BUDGET="${WEBVIDEO_E2E_LONG_DROP_RATIO_BUDGET:-0.01}"
    export WEBVIDEO_E2E_LONG_BACKEND_DROP_RATIO_BUDGET="${WEBVIDEO_E2E_LONG_BACKEND_DROP_RATIO_BUDGET:-0.01}"
    export WEBVIDEO_E2E_LONG_SEQUENCE_GAP_FRAME_BUDGET="${WEBVIDEO_E2E_LONG_SEQUENCE_GAP_FRAME_BUDGET:-0}"
    export WEBVIDEO_E2E_LONG_SEVERE_HITCH_BUDGET="${WEBVIDEO_E2E_LONG_SEVERE_HITCH_BUDGET:-0}"
    export WEBVIDEO_E2E_LONG_FRAME_HITCH_RATIO_BUDGET="${WEBVIDEO_E2E_LONG_FRAME_HITCH_RATIO_BUDGET:-0.005}"
    : "${CHROME_WEBGPU_EXECUTABLE:=/usr/bin/google-chrome-stable}"
    export CHROME_WEBGPU_EXECUTABLE
    ;;
  hardware-mixed-4k-long)
    export WEBVIDEO_PLAYWRIGHT_CHROME_WEBGPU=1
    export WEBVIDEO_REQUIRE_HARDWARE_WEBGPU=1
    export WEBVIDEO_E2E_LONG=1
    export WEBVIDEO_E2E_4K=1
    export START_4K_RTSP=1
    export WEBVIDEO_E2E_LONG_CHANNELS="${WEBVIDEO_E2E_LONG_CHANNELS:-channel-4k,channel-003,channel-001}"
    export WEBVIDEO_E2E_LONG_DURATION_MS="${WEBVIDEO_E2E_LONG_DURATION_MS:-180000}"
    export WEBVIDEO_E2E_LONG_MIN_FPS_RATIO="${WEBVIDEO_E2E_LONG_MIN_FPS_RATIO:-0.25}"
    export WEBVIDEO_E2E_LONG_FRAME_INTERVAL_P95_BUDGET_MS="${WEBVIDEO_E2E_LONG_FRAME_INTERVAL_P95_BUDGET_MS:-300}"
    export WEBVIDEO_E2E_LONG_S2R_P95_BUDGET_MS="${WEBVIDEO_E2E_LONG_S2R_P95_BUDGET_MS:-30000}"
    export WEBVIDEO_E2E_LONG_R2R_P95_BUDGET_MS="${WEBVIDEO_E2E_LONG_R2R_P95_BUDGET_MS:-1200}"
    export WEBVIDEO_E2E_LONG_DROP_RATIO_BUDGET="${WEBVIDEO_E2E_LONG_DROP_RATIO_BUDGET:-0.10}"
    export WEBVIDEO_E2E_LONG_BACKEND_DROP_RATIO_BUDGET="${WEBVIDEO_E2E_LONG_BACKEND_DROP_RATIO_BUDGET:-0.50}"
    export WEBVIDEO_E2E_LONG_SEQUENCE_GAP_FRAME_BUDGET="${WEBVIDEO_E2E_LONG_SEQUENCE_GAP_FRAME_BUDGET:-5000}"
    export WEBVIDEO_E2E_LONG_SEVERE_HITCH_BUDGET="${WEBVIDEO_E2E_LONG_SEVERE_HITCH_BUDGET:-1000}"
    export WEBVIDEO_E2E_LONG_FRAME_HITCH_RATIO_BUDGET="${WEBVIDEO_E2E_LONG_FRAME_HITCH_RATIO_BUDGET:-0.35}"
    : "${CHROME_WEBGPU_EXECUTABLE:=/usr/bin/google-chrome-stable}"
    export CHROME_WEBGPU_EXECUTABLE
    ;;
  hardware-duplicate-4k60-profile)
    export WEBVIDEO_PLAYWRIGHT_CHROME_WEBGPU=1
    export WEBVIDEO_REQUIRE_HARDWARE_WEBGPU=1
    export WEBVIDEO_CHROME_WEBGPU_PRESET="${WEBVIDEO_CHROME_WEBGPU_PRESET:-strict-vulkan}"
    export WEBVIDEO_E2E_PROFILE=1
    export WEBVIDEO_PROFILE_STREAM_SETS="${WEBVIDEO_PROFILE_STREAM_SETS:-channel-4k-crowd,channel-4k-crowd,channel-003}"
    export WEBVIDEO_PROFILE_EXPECT_RTSP_SOURCES="${WEBVIDEO_PROFILE_EXPECT_RTSP_SOURCES:-channel-4k-crowd=cctv-road-crowd-1080p24,channel-003=cctv-floor-1080p}"
    export WEBVIDEO_PROFILE_ASSERT_STABLE="${WEBVIDEO_PROFILE_ASSERT_STABLE:-1}"
    export WEBVIDEO_PROFILE_MIN_RENDER_FPS="${WEBVIDEO_PROFILE_MIN_RENDER_FPS:-14}"
    export WEBVIDEO_PROFILE_DURATION_MS="${WEBVIDEO_PROFILE_DURATION_MS:-60000}"
    export WEBVIDEO_PROFILE_SAMPLE_INTERVAL_MS="${WEBVIDEO_PROFILE_SAMPLE_INTERVAL_MS:-1000}"
    export WEBVIDEO_SAMPLE_FOOTAGE="${WEBVIDEO_SAMPLE_FOOTAGE:-1}"
    export START_4K_RTSP=1
    export START_4K_STRESS_RTSP=1
    : "${CHROME_WEBGPU_EXECUTABLE:=/usr/bin/google-chrome-stable}"
    export CHROME_WEBGPU_EXECUTABLE
    ;;
  hardware-media-worker-profile)
    export WEBVIDEO_PLAYWRIGHT_CHROME_WEBGPU=1
    export WEBVIDEO_REQUIRE_HARDWARE_WEBGPU=1
    export WEBVIDEO_CHROME_WEBGPU_PRESET="${WEBVIDEO_CHROME_WEBGPU_PRESET:-strict-vulkan}"
    export WEBVIDEO_E2E_MEDIA_WORKER=1
    export WEBVIDEO_E2E_PROFILE=1
    export WEBVIDEO_VMS_MEDIA_WORKER=1
    export WEBVIDEO_PROFILE_STREAM_SETS="${WEBVIDEO_PROFILE_STREAM_SETS:-channel-4k-crowd,channel-4k-crowd,channel-003}"
    export WEBVIDEO_PROFILE_EXPECT_RTSP_SOURCES="${WEBVIDEO_PROFILE_EXPECT_RTSP_SOURCES:-channel-4k-crowd=cctv-road-crowd-1080p24,channel-003=cctv-floor-1080p}"
    export WEBVIDEO_PROFILE_ASSERT_STABLE="${WEBVIDEO_PROFILE_ASSERT_STABLE:-1}"
    export WEBVIDEO_PROFILE_MIN_RENDER_FPS="${WEBVIDEO_PROFILE_MIN_RENDER_FPS:-14}"
    export WEBVIDEO_PROFILE_DURATION_MS="${WEBVIDEO_PROFILE_DURATION_MS:-60000}"
    export WEBVIDEO_PROFILE_SAMPLE_INTERVAL_MS="${WEBVIDEO_PROFILE_SAMPLE_INTERVAL_MS:-1000}"
    export WEBVIDEO_SAMPLE_FOOTAGE="${WEBVIDEO_SAMPLE_FOOTAGE:-1}"
    export START_4K_RTSP=1
    export START_4K_STRESS_RTSP=1
    : "${CHROME_WEBGPU_EXECUTABLE:=/usr/bin/google-chrome-stable}"
    export CHROME_WEBGPU_EXECUTABLE
    ;;
  4k)
    export WEBVIDEO_E2E_4K=1
    export START_4K_RTSP=1
    ;;
  hardware-4k)
    export WEBVIDEO_PLAYWRIGHT_CHROME_WEBGPU=1
    export WEBVIDEO_REQUIRE_HARDWARE_WEBGPU=1
    export WEBVIDEO_E2E_4K=1
    export START_4K_RTSP=1
    : "${CHROME_WEBGPU_EXECUTABLE:=/usr/bin/google-chrome-stable}"
    export CHROME_WEBGPU_EXECUTABLE
    ;;
  *)
    echo "Unknown WEBVIDEO_TEST_PROFILE='${WEBVIDEO_TEST_PROFILE}'." >&2
    echo "Supported profiles: default, hardware-gpu, long, hardware-long, hardware-vms-profile, hardware-60fps, hardware-mixed-4k-long, hardware-duplicate-4k60-profile, hardware-media-worker-profile, 4k, hardware-4k." >&2
    exit 2
    ;;
esac

run_step() {
  local label=$1
  shift

  echo
  echo "==> $label"
  "$@"
}

run_step "backend unit/spec/demo-host tests" "$ROOT_DIR/scripts/test-backend.sh"
run_step "frontend unit/contract tests" "$ROOT_DIR/scripts/test-frontend-unit.sh"
run_step "frontend TypeScript typecheck" "$NPM_BIN" --prefix "$ROOT_DIR/frontend" exec -- tsc -p "$ROOT_DIR/frontend/tsconfig.json" --noEmit

if [[ "${SKIP_E2E:-0}" == "1" || "${SKIP_E2E:-}" == "true" ]]; then
  echo
  echo "==> frontend Playwright e2e skipped by SKIP_E2E=${SKIP_E2E}"
else
  run_step "frontend Playwright e2e" "$ROOT_DIR/scripts/test-frontend-e2e.sh"
fi

echo
echo "All requested tests passed."
